### ISSUE TITLE
TEAM 1: New user sign up

### ISSUE THREAD

**Issue by iconoclastpython** [CS673S15-Group1/Final_Project#25]
It seems that a new user only can sign up in the command line by "createsuperuser", while the sign up in welcome page is useless.

After I sign up  a new user in the welcome page, the username didn't appear in the "user list" in any of the project I made.

**Comment by mraaa** [comment]
Please notice what we had before.(In our meeting minutes)
After sign up, you need go to admin portal to activate the account !!

**Comment by malmanzor** [comment]
Yes, this was a requirement given to us by the professor. A user should be able to register, but admin approval is required before a user can actually access the system. A user created by createsuperuser is automatically given all permissions, including 'active.'

**Comment by iconoclastpython** [comment]
OK.. I see, Thanks!
